services:
  # Backend Service - FastAPI
  - type: web
    name: nlw-agents-backend
    runtime: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://jeyjey2025cyborg:kjcd5588@cluster0.jkp7hed.mongodb.net/ai-let-me-ask?retryWrites=true&w=majority&appName=Cluster0&ssl=true&ssl_cert_reqs=CERT_NONE
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
    autoDeploy: true
    rootDir: backend
    plan: free
    region: oregon
    branch: main

  # Frontend Service - React Static Site
  - type: web
    name: nlw-agents-frontend  
    runtime: node
    buildCommand: |
      cd frontend
      yarn install
      yarn build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: nlw-agents-backend
          property: host
    autoDeploy: true
    rootDir: frontend
    plan: free
    region: oregon
    branch: main
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    redirects:
      - source: /*
        destination: /index.html
        type: rewrite
    routes:
      - type: rewrite
        source: /api/*
        destination: https://nlw-agents-backend.onrender.com/api/*